################################################
#           Docker Compose Commands            #
################################################
# 1. 
#   To start docker by building image
#   -> docker-compose up --build
#
#   To start docker compose file in background
#   -> docker-compose up -d
#
#
# 2. 
#   To stop docker compose file from backgroud
#   -> docker-compose down
#
# 3. 
#   To break the running project
#   -> ctrl + c 
#
##################################################
#
# References:
#
# 1. Redis: 
# https://hub.docker.com/r/bitnami/redis/
# https://raw.githubusercontent.com/bitnami/containers/main/bitnami/redis/docker-compose.yml
# 
# 2. mongodb
# https://hub.docker.com/r/bitnami/mongodb
# https://raw.githubusercontent.com/bitnami/containers/main/bitnami/mongodb/docker-compose.yml
#
# 3.
# 
#
################################################

version: "1"
services:

################################################
#           Dotnet core project                #
################################################

    # dotnetcore:
    #     build: .
    #     container_name: dotnetcore_container
    #     ports:
    #         - "8010:80"

  dotnetcore:
    container_name: dotnetcore_container
    image: ${DOCKER_REGISTRY-}dotnetcore
    build:
      context: .
      dockerfile: src/DotNetCore.API/Dockerfile        
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_CONNECTION_STRING= redis:6379
    ports:
      - "8010:80"
    command: 
      echo "test"
    depends_on:
      - postgres
      - redis
    #  - microsoftsql_database
          
################################################
#                    Redis                     #
################################################

  redis:
    container_name: redis_container
    image: docker.io/bitnami/redis:7.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL      
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

################################################
#               MS SQL Database                #
################################################

  microsoftsql_database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: microsoftsql_server_container
    environment:
        SA_PASSWORD: "Admin@123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    volumes:
      - 'microsoftsql_data:/bitnami/server'

################################################
#                   Mongodb                    #
################################################

  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    container_name: mongodb_container
    restart: unless-stopped
    environment:
      - MONGO_ININDB_DATABASE=dotnetcore_db
      - MONGO_INITDB_ROOT_USERNAME=dncdb
      - MONGO_INITDB_ROOT_PASSWORD=dncdb!123
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

################################################
#                   Postgres                   #
################################################

  postgres:
    image: "postgres:latest"
    container_name: postgres_server
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yourdatabasename
    volumes:
      - pgdata:/var/lib/postgresql/data:z
    ports:
      - 5433:5432

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  microsoftsql_data:
    driver: local
  pgdata:
    driver: local